In [19]:
import numpy as np
# Numpy内置函数

# randn()返回具有标准正态分布的序列
arr = np.random.randn(2,3)
print(arr)

# np.ceil()函数:向上最接近的整数,参数是number或者array
print(np.ceil(arr))

# np.floor()函数:向下最接近的整数,参数number或者是array
print(np.floor(arr))

# np.rint(): 四舍五入,参数是number或者是array
print(np.rint(arr))

# np.isnan(): 判断元素是否为NaN(not a Number),参数是number或 array
print(np.isnan(arr))

# np.multiply():元素相乘,参数是number或者array
multiply = np.multiply(arr,arr)
print(multiply)
# print([np.ndarray.__format__(x) for x in multiply])

# np.divide(): 元素相除,参数number或者array
print(np.divide(arr,arr))

# np.abs(): 元素的绝对值,参数是number或者array
print(np.abs(arr))

# np.where(condition,x,y):三元运算符, x if condition else y
print(np.where(arr > 0,1,-1))

print('-'*34)

# np.mean(), np.sum()：所有元素的平均值，所有元素的和，参数是 number 或 array
print(np.mean(arr))
print(np.sum(arr))
print('-'*34)

# np.max(), np.min()：所有元素的最大值，所有元素的最小值，参数是 number 或 array
print(np.max(arr))
print(np.min(arr))
print('-'*34)

# np.std(), np.var()：所有元素的标准差，所有元素的方差，参数是 number 或 array


# 标准差 (Standard Deviation)

# 标准差是方差的平方根。由于方差是平方的结果，它的单位是原始数据单位的平方。因此，标准差通过对方差开根号，
# 恢复到与原数据相同的单位。

# 公式：

# 标准差 
# 𝜎
# σ 的公式为：σ=√1/n*(i=1)∑(n)(xi-u)2
print(np.std(arr))


# 方差（Variance）的表达式有着深刻的数学背景，主要用于量化一个随机变量或一组数据点的分散程度。
# 为了理解方差的由来，首先从数据的分布和概率的角度来分析。我们将详细讲解方差公式的推导过程以及其数学意义。
# 1. 为什么要有方差？
# 在统计学中，我们关心的一个重要问题是数据的分散程度。假设我们有一组数据，了解它们的均值（期望值）很重要，
# 但单纯的均值并不能提供关于数据如何围绕均值分布的信息。例如，在两个数据集均值相同的情况下，
# 一个数据集可能聚集在均值附近，而另一个数据集则可能较为分散。
# 因此，方差作为一个度量，用来表达数据如何围绕均值散布，进而反映了数据的波动性或变异性。
# 方差衡量的是数据点与均值之间的平均距离的平方。具体而言，它是所有数据点与均值之差的平方的平均值
# 表达式: σ2=1/n*(i=1)∑(n)(xi-u)2
# 其中：
# 𝜇是数据的均值。
# 𝑥𝑖是数据中的每一个值。
# 𝑛 是数据的总个数。
# 方差的作用：
# 方差越大，说明数据的分布越广，离均值的距离越大。
# 方差越小，说明数据更加集中，离均值较近。
print(np.var(arr))
print('-'*34)

# np.argmax(), np.argmin()：最大值的下标索引值，最小值的下标索引值，参数是 number 或 array
print(np.argmax(arr))
print(np.argmin(arr))
print('-'*34)

# np.cumsum(), np.cumprod()：返回一个一维数组，每个元素都是之前所有元素的 累加和 和 累乘积，参数是 number 或 array
print(np.cumsum(arr))
print(np.cumprod(arr))
print('-'*34)

#   多维数组默认统计全部维度，axis参数可以按指定轴心统计，值为0则按列统计，值为1则按行统计。
# 创建一个 2x3 的二维数组
arr = np.array([[1, 2, 3], [4, 5, 6]])

# 对整个数组进行求和
total_sum = np.sum(arr)
print(total_sum)

print('-'*34)

# 2. 使用 axis 参数
# axis 参数用于指定在多维数组中沿着哪一个轴进行操作。NumPy 数组可以有多个维度，例如，二维数组的维度是 (m, n)，表示有 m 行和 n 列。轴的索引是从 0 开始的。
# axis=0：表示沿着 列 方向进行操作，也就是“垂直”方向。
# axis=1：表示沿着 行 方向进行操作，也就是“水平方向”。
# 示例 1：按 列 统计（axis=0）
# 当 axis=0 时，我们是 按列 对数组进行统计，也就是说，我们会对每一列的所有元素进行操作。

arr = np.array([[1, 2, 3], [4, 5, 6]])

# 按列求和，axis=0
sum_by_column = np.sum(arr, axis=0)
print(sum_by_column)
print('-'*34)

# 按行求和，axis=1
sum_by_row = np.sum(arr, axis=1)
print(sum_by_row)
print('-'*34)

# 去重函数 np.unique():找到唯一的值并返回排序结果,类似与python的set
np_randint = np.random.randint(1,5,size = (3,4))
print(np_randint)
print(np.unique(np_randint))
print('-'*34)

# 排序函数
np_arr = np.array([1,2,34,5])
print('原数组:',np_arr)

# 使用np.sort()函数进行排序,返回排序后的副本
np_sort = np.sort(np_arr)
print('numpy.sort函数排序后的数组',np_sort)

# ndarray直接调用sort,在原数组上进行修改
np_arr.sort()
print('数组.sort()函数方法排序:',np_arr)


[[ 0.98415951  0.0130941  -0.81224602]
 [ 0.18869249 -0.38592436 -0.71259237]]
[[ 1.  1. -0.]
 [ 1. -0. -0.]]
[[ 0.  0. -1.]
 [ 0. -1. -1.]]
[[ 1.  0. -1.]
 [ 0. -0. -1.]]
[[False False False]
 [False False False]]
[[9.68569937e-01 1.71455472e-04 6.59743598e-01]
 [3.56048562e-02 1.48937611e-01 5.07787890e-01]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.98415951 0.0130941  0.81224602]
 [0.18869249 0.38592436 0.71259237]]
[[ 1  1 -1]
 [ 1 -1 -1]]
----------------------------------
-0.12080277538320178
-0.7248166522992107
----------------------------------
0.984159507997766
-0.8122460207716379
----------------------------------
0.610089540443448
0.37220924735849753
----------------------------------
0
2
----------------------------------
[ 0.98415951  0.99725361  0.18500759  0.37370008 -0.01222428 -0.72481665]
[ 9.84159508e-01  1.28866837e-02 -1.04671575e-02 -1.97507403e-03
  7.62229178e-04 -5.43158698e-04]
----------------------------------
21
----------------------------------
[5 7 9]
---------------