In [8]:
import numpy as np

# 数组的算数运算是按照元素的。新的数组被创建并且被结果填充
a = np.array([20,30,40,50])
b = np.arange(4)
c = a - b
print('数组a:',a)
print('数组b:',b)
print('数组运算a-b:',c)
print('-'*34)

# 2 矩阵乘法 矩阵对应元素的乘法（multiplication by element-wise）
d = np.random.randint(1,5,size=(3,4))
print('d:',d)
e = np.random.randint(6,10,size=(3,4))
print('e:',e)
f = d * e
print('f:',f)

g = np.multiply(d,e)
print('g:',g)
print('-'*34)

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,23],[-1,7],[8,9]])

print('x.dot(y):',x.dot(y))
print('np.dot(x,y):',np.dot(x,y))




数组a: [20 30 40 50]
数组b: [0 1 2 3]
数组运算a-b: [20 29 38 47]
----------------------------------
d: [[1 2 3 3]
 [2 2 4 4]
 [4 3 3 3]]
e: [[8 8 7 6]
 [6 7 6 7]
 [9 7 9 9]]
f: [[ 8 16 21 18]
 [12 14 24 28]
 [36 21 27 27]]
g: [[ 8 16 21 18]
 [12 14 24 28]
 [36 21 27 27]]
----------------------------------
x.dot(y): [[ 28  64]
 [ 67 181]]
np.dot(x,y): [[ 28  64]
 [ 67 181]]
