In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as ps

a = np.array([1,2,3,4,5])
# np.arange() 可以生成一个等差数列。
b =  np.arange(0,10,1)
# 3.3 创建二维数组（矩阵）
c = np.array([[1,2],[3,4],[5,6]])
# 3.4 使用 zeros 和 ones 创建数组
# np.zeros()：创建全是 0 的数组。
# np.ones()：创建全是 1 的数组。
d = np.zeros((2,3)) #2行3列矩阵数据
e = np.ones((3,3)) #3行3列数组
print(a)
print(b)
print(c)
print(d)
print(e)

np_arange = np.arange(10,20,5,dtype = int)
print(np_arange)
print(f'np_arrange的元素类型:{np_arange.dtype}')
print(f'np_arrange的元素类型:{type(np_arange)}')
print('-'*34)

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[[1 2]
 [3 4]
 [5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[10 15]
np_arrange的元素类型:int64
np_arrange的元素类型:<class 'numpy.ndarray'>
----------------------------------


In [2]:
import numpy as np
# 生成指定维度大小(3行4列)的随机多为浮点型数据(二维),rand固定位0.0-0.1
arr = np.random.rand(3,4)
print(arr)
print(type(arr))
print('-'*34)
# 生成指定维度大小(3行4列)的随机多为整数型数据(二维),rand固定位(-1,5)
np_randint = np.random.randint(-1,5,size = (3,4))
print(f'np_randint:{np_randint}')
print(type(np_randint))
print('-'*34)
# 生成指定维度大小(3行4列)的随机多为浮点型数据(二维),uniform可以指定区间(-1,5),产生-1到5之间分布均匀的样本值
np_unifrom = np.random.uniform(-1,5,size = (4,5))
print(np_unifrom)
print(type(np_unifrom))
print('-'*34)
# 1. dtype参数，指定数组的数据类型，类型名+位数，如float64, int32
# 2. astype方法，转换数组的数据类型
zeros_float_arr = np.zeros((3,4),dtype = np.float64)
print(zeros_float_arr)
print(type(zeros_float_arr))
print('-'*34)
# astype转换数据类型,将已有的数组的数据类型转换为int32
zzeros_int_arr = zeros_float_arr.astype(np.int32)
print(zzeros_int_arr)
print(type(zzeros_int_arr))
print('-'*34)

[[0.46941306 0.09540589 0.86258652 0.58753991]
 [0.89996659 0.19964087 0.77139293 0.00908699]
 [0.81309644 0.93538999 0.8509107  0.11055098]]
<class 'numpy.ndarray'>
----------------------------------
np_randint:[[ 0  0  3 -1]
 [ 4  3  4 -1]
 [ 0  1  4 -1]]
<class 'numpy.ndarray'>
----------------------------------
[[-0.80838529  2.47791328 -0.88377436  3.72742281  1.13748238]
 [ 1.1160142   1.1385354   3.20236267  1.22336153  1.44954635]
 [ 3.15518696  0.83749346  4.88734627  1.18404948  3.96139159]
 [ 4.4348625   1.96724843  4.49804419  2.80074921  1.89554463]]
<class 'numpy.ndarray'>
----------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
----------------------------------
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
<class 'numpy.ndarray'>
----------------------------------


In [4]:
# 等比/等差数列
# np.logspace 等比数列
# logsapace中开始点和结束点是10的幂
# 我们让开始点为0,结束点为0,元素个数为10,看看输出结果
logspace = np.logspace(0,0,10)
print(logspace)
print(type(logspace))
print('-'*34)

# [ 1, 10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000, 1000000000]
logspace2 = np.logspace(0,9,10)
print(logspace2)
print(type(logspace2))
print([f"{x:.0f}" for x in logspace2])
print(logspace2.dtype)
print('-'*34)

# logspace中，开始点和结束点是10的幂
# 假如，我们想要改变基数，不让它以10为底数，我们可以改变base参数，将其设置为2
np_logspace_base2 = np.logspace(0,9,10,base=2)
print(np_logspace_base2)
print(np_logspace_base2.dtype)
print([f'{x:.0f}' for x in np_logspace_base2])
print('-'*34)

# 可以使用参数endpoint来决定是否包含终止值，默认值为True。

# 这是因为 endpoint=False 的作用会导致 logspace 返回的是从10**1到 接近 10**10（但不包含）
# 的均匀分布的对数间隔数值，而不是简单的按指数增长。
# 在 endpoint=False 情况下，logspace 会根据起始和终止值的对数，均匀地生成 10 个数值，
# 这些值并不会严格是 10, 100, 1000,... 的样式，而是对数间隔的数值。

np_eendpoint_False = np.logspace(1,10,10,endpoint=False)
print(np_eendpoint_False)
print([f'{x:.0f}' for x in np_eendpoint_False])

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
----------------------------------
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]
<class 'numpy.ndarray'>
['1', '10', '100', '1000', '10000', '100000', '1000000', '10000000', '100000000', '1000000000']
float64
----------------------------------
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
float64
['1', '2', '4', '8', '16', '32', '64', '128', '256', '512']
----------------------------------
[1.00000000e+01 7.94328235e+01 6.30957344e+02 5.01187234e+03
 3.98107171e+04 3.16227766e+05 2.51188643e+06 1.99526231e+07
 1.58489319e+08 1.25892541e+09]
['10', '79', '631', '5012', '39811', '316228', '2511886', '19952623', '158489319', '1258925412']
